# Generated by Django 4.2 on 2023-04-17 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Employee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("empid", models.IntegerField()),
                ("empfirstname", models.CharField(max_length=30)),
                ("emplastname", models.CharField(max_length=30)),
            ],
        ),
    ]
